on:
  push:
    branches: [ prod ]
   #pull_request:
     #branches: [ prod ]
     #types:
      #- closed
      #- merged
   #status: {}    
name: 🚀 FTP Deploy
jobs:
  FTP-Deploy-Action:
    name: 🎉 FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: 📂 FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: u202468932
        password: ${{ secrets.FTP_PASSWORD }}
