on:
  push:
    branches: [ prod ]
   #pull_request:
     #branches: [ prod ]
     #types:
      #- closed
      #- merged
   #status: {}    
name: 🚀 FTP Deploy
jobs:
  FTP-Deploy-Action:
    name: 🎉 FTP-Deploy-Action
    runs-on: ubuntu-16.04
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: 📂 FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://185.28.21.159/https://barralounge.com.br//
        ftp-username: u202468932
        ftp-password: ${{ secrets.FTP_PASSWORD }}
